### ISSUE TITLE
Exceeded Prepaid Gas Error During "near call purchase_in_escrow contract method"

### ISSUE THREAD

**Issue by kasodon** [near-examples/escrow-js#1]
This error occurs due to not having enough TGas attached to the cross-contract call.  Default TGas attached is 30TGas but the contract needs up to 50TGas to execute the contract method successfully. Please refer to this [StackOverflow ans](https://stackoverflow.com/questions/70452485/exceeded-prepaid-gas-common-solutions) to learn more about this error. 
**NOTE:**  You must attach your TGas as an additional parameter in _NEAR CLI_ like so --gas=100000000000000

**Comment by idea404** [comment]
Would be helpful to add these steps for "interacting with this contract using NEAR CLI" to `README.md`

**Comment by kasodon** [comment]
Definitely! give me a sec
